server.port=8105
### DB
spring.datasource.url=jdbc:postgresql://localhost:5432/car-rental
spring.datasource.username=postgres
spring.datasource.password=postgres
### Properties configuration
car-rental.events-queue-provider=none
### KEYCLOAK CONFIGURATION
spring.security.oauth2.resource-server.jwt.issuer-uri=http://localhost:8081/realms/master
### RABBITMQ CONFIGURATION
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
### KAFKA CONFIGURATION
spring.kafka.bootstrap-servers=localhost:9092