# Flyway
### DB
spring.flyway.locations=classpath:changesets
### Properties configuration
# Price per day configuration
car-rental.price-per-day=50.0
car-rental.events-queue-provider=none
### KEYCLOAK CONFIGURATION
spring.security.oauth2.resource-server.jwt.issuer-uri=http://localhost:0/realms/master
### RABBITMQ CONFIGURATION
spring.rabbitmq.username=it
spring.rabbitmq.password=it
### KAFKA CONFIGURATION
spring.kafka.bootstrap-servers=localhost:0