# fly.toml app configuration file generated for car-rental-terraform-storage on 2025-02-27T15:32:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'car-rental-terraform-storage'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 9001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 9000
  protocol = "tcp"

[[services.ports]]
  port = 9000
  handlers = ["tls"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
    source = "car_rental_terraform_storage"
    destination = "/data"